### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by filfreire** [yegor256/rehttp#13]
Tasks:
* Follow Github guideline https://github.com/blog/1184-contributing-guidelines of having a separate contributing file
* Create "How to contribute" section with a link to CONTRIBUTING.md

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire fixed in 3c95794

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rehttp#13` is not in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/rehttp#13`.
