### ISSUE TITLE
ignore everything that is lower than 500

### ISSUE THREAD

**Issue by yegor256** [yegor256/rehttp#19]
All response codes that are lower than 500 should not lead to retries.

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#19` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#19](https://github.com/yegor256/rehttp/issues/19) was not in scope
