### ISSUE TITLE
badge is not rendered by GitHub

### ISSUE THREAD

**Issue by yegor256** [yegor256/rehttp#23]
Check this: https://github.com/zerocracy/farm/blob/master/README.md

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by 0crat** [comment]
Job [#23](https://github.com/yegor256/rehttp/issues/23) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#23` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#23](https://github.com/yegor256/rehttp/issues/23) is now out of scope
