### ISSUE TITLE
Looks like rehttp.net is down.

### ISSUE THREAD

**Issue by proofit404** [yegor256/rehttp#29]
Hi,

Front page is working ok.

I have persistent problems with repeater part. The timeout error happen all the time. I would be happy to help to solve the problem.

See screenshots below for more details.

##### Enabled

![Bad](https://user-images.githubusercontent.com/1862725/102614472-5a643e80-4145-11eb-91ae-8b4b3dc9872e.png)

##### Disabled

![Good](https://user-images.githubusercontent.com/1862725/102614498-66500080-4145-11eb-94c7-c93bfed68156.png)

Best regards,
Artem.

**Comment by yegor256** [comment]
@proofit404 it was a temporary issue, thanks for reporting

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#29` is not assigned, can't get performer
