### ISSUE TITLE
age of request to show

### ISSUE THREAD

**Issue by yegor256** [yegor256/rehttp#8]
Let's show it

**Comment by 0crat** [comment]
I'm not managing ` yegor256/rehttp ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.

**Comment by yegor256** [comment]
@rultor release, tag is `0.6`

**Comment by 0crat** [comment]
I'm not managing ` yegor256/rehttp ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.
